### ISSUE TITLE
Appears to cause UE4 to crash after latest fortnite update

### ISSUE THREAD

**Issue by SephirothSG** [JokerakaXRAY/FortHook#4]
Will continue testing various methods of injection etc, however it appears that UE4 is crashing once in-game with this injected.

edit: Am also using noeye

**Comment by SephirothSG** [comment]
Possibly related to ESP as crashes immediately when ESP is enabled in-game, lowering maxdist yields the same result

**Comment by SephirothSG** [comment]
Appears to crash after a short period with the aimbot enabled also, odd.

**Comment by SephirothSG** [comment]
Can confirm both the aimbot and ESP appear to be causing the crashes, ESP crashes the game immediately when/if enabled in-game and the aimbot after a short while with it enabled.

**Comment by JokerakaXRAY** [comment]
Because the SDK is outdated!
Will update when I have time.
